// Campaign Kit — turn a generated campaign into a self-contained, brand-styled
// HTML one-pager the agency can hand to a client. Shared by the Studio and the
// per-job campaign in the Job board.

import type { Campaign } from './api';

export function buildCampaignKitHtml(c: Campaign): string {
  const esc = (s: string): string => String(s ?? '').replace(/[&<>]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[m] as string));
  const social = c.social.map((s) => `
    <section class="post">
      <div class="tag">${esc(s.platform.toUpperCase())}</div>
      <div class="body">${esc(s.body).replace(/\n/g, '<br>')}</div>
      ${s.hashtags.length ? `<div class="tags">${esc(s.hashtags.join(' '))}</div>` : ''}
    </section>`).join('');
  const block = (label: string, val: string): string => val ? `<section class="blk"><div class="lbl">${label}</div><div class="val">${esc(val)}</div></section>` : '';
  return `<!DOCTYPE html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(c.headline)} — Campaign Kit</title>
<style>
  :root { --bg:#0A0A0A; --ink:#fff; --muted:#9a958c; --accent:#FF6008; --line:#26241f; }
  * { box-sizing:border-box; } body { margin:0; background:var(--bg); color:var(--ink); font-family:"Inter","Helvetica Neue",Arial,sans-serif; line-height:1.55; }
  .wrap { max-width:820px; margin:0 auto; padding:56px 28px 80px; }
  .kicker { font-family:"JetBrains Mono",monospace; font-size:11px; letter-spacing:.22em; text-transform:uppercase; color:var(--accent); }
  h1 { font-size:38px; line-height:1.12; letter-spacing:-.02em; margin:10px 0 14px; }
  .lede { font-size:17px; color:#d7d2c8; }
  .dot { display:inline-block; width:12px; height:12px; border-radius:50%; background:var(--accent); margin-left:4px; }
  .hero { width:100%; border-radius:14px; margin:28px 0; display:block; }
  .blk { border-top:1px solid var(--line); padding:18px 0; }
  .lbl { font-family:"JetBrains Mono",monospace; font-size:10px; letter-spacing:.18em; text-transform:uppercase; color:var(--muted); margin-bottom:6px; }
  .val { font-size:15px; color:#ece8e0; }
  h2 { font-size:13px; font-family:"JetBrains Mono",monospace; letter-spacing:.18em; text-transform:uppercase; color:var(--muted); margin:40px 0 12px; }
  .post { border:1px solid var(--line); border-radius:12px; padding:16px 18px; margin-bottom:12px; }
  .post .tag { font-family:"JetBrains Mono",monospace; font-size:9px; letter-spacing:.14em; color:var(--accent); margin-bottom:8px; }
  .post .body { font-size:15px; color:#ece8e0; } .post .tags { color:var(--accent); margin-top:10px; font-size:14px; }
  footer { margin-top:48px; border-top:1px solid var(--line); padding-top:18px; color:var(--muted); font-size:12px; font-family:"JetBrains Mono",monospace; letter-spacing:.12em; }
</style></head><body><div class="wrap">
  <div class="kicker">B&amp;B Markenagentur · Kampagne</div>
  <h1>${esc(c.headline)}<span class="dot"></span></h1>
  <div class="lede">${esc(c.big_idea)}</div>
  ${c.hero_image_path ? `<img class="hero" src="${esc(c.hero_image_path)}" alt="Key visual">` : ''}
  ${block('Key message', c.key_message)}
  ${c.channels.length ? block('Channels', c.channels.join(' · ')) : ''}
  ${social ? `<h2>Social</h2>${social}` : ''}
  ${block('Key visual — image brief', c.image_brief)}
  ${block('Video — teaser brief', c.video_brief)}
  ${c.deck_title ? block('Deck', `${c.deck_title} · ${c.deck_slides} slides (separate file)`) : ''}
  <footer>Generated by BLAIQ · brand-locked (DNA + Tone + Hivemind) · ${esc(c.model)}</footer>
</div></body></html>`;
}

export function openCampaignKit(c: Campaign, download = false): void {
  const html = buildCampaignKitHtml(c);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  if (download) {
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(c.headline || 'campaign').replace(/[^\w-]+/g, '_')}_kit.html`;
    document.body.appendChild(a); a.click(); a.remove();
  } else {
    window.open(url, '_blank');
  }
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}
